# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:prOZGxgF5AYWMYPz0cGucXyhhPSA,iv:FHzq3xIBSeh2I3ki3XDIRj86QcfCw0gTKZxaVxtBZYQ=,tag:cbYZZfwsmAZP8jU4G+ifFg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:wAgNyxytGUzu4ui/Y0BANb5fO/akrSw0hz609H+QjkFHhn7eig==,iv:Dcoqxhj8B63apeVUrxXOCfCiOO5pzJkCr8iIqXjD9Bo=,tag:0cN4+s7BR8OzLYaU/75tjQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:HApTBtB+g2/YyZvWlX3/FA==,iv:knmBeIxPhudvyZT4fB65+0qmN3QreZuQzF0w3vjIglY=,tag:KlrCns0p7H1aUwHmzdh5XA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cg8jk89nugmrn3rylak4shyaq2ssgvp2g6975884zp3u2t8klenqx9cnau
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTGZQSzMxZVQrcjNMVzBH
            Y0Z3aWM0Sm5ubjJpajVmVk03TEoxaWZwb2xRClZkeHJwdytJUXBRaEljNkNuYmEy
            U1Bab0NHdzBkK24zWUJNR01PcU9Ha3cKLS0tIDBNR3Y5QjRvRFZFVFdiU3NHUXpT
            SDNSVW53QmlLWkZXL0lrdzdqZThKOVUKABrK228pztKXmJYI0pUCJUJEiVPGY5os
            l3yn6V7H5+Gf4qE3apOTpW2YoqZg6LCA/9PvfvUg2pE98cNvfo3p2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T15:06:11Z"
    mac: ENC[AES256_GCM,data:vf7GFKofVqkrwawl1BE5Ejj8lCdNZ2BgoZV8OK7x1G5eBcDonm7Y1XIxPlV2XShXtl1toW0pqkDBKgGK8dlXs0CuyuGb0uqv67bIjhwVG0FoDsWGNcGFSgnYmSGBIP9JXObhOojLzvDP/Xu/MtdXff6y3wYHt9cRwrkID/ix/FA=,iv:p3remoc0HdSjK3DAA5GofhiFYXEwnPULtb0kaaSb/KU=,tag:gw0V9JsBp+d6gtgu/srozQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
