# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:/DpjYWXp4gk8raNrZDBNzcN9Q7FQ,iv:99gCe0BWdXdiKuI8kseD+h96P6OJCWh745tvtLQwlwQ=,tag:e92yQyk8ETO2aORH/8jL6w==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:t4b8fYDrQ4ZvA/zyQe7tPY0tDlMaGR8t/mwlObzrxm6vpcAQHg==,iv:WSsj0ofnEof0bJ/hx8H1LUfK+3sW/xWtOEaBQC0RQkI=,tag:y+7tGmo/K2JYZXC/a+DWpQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:oMZLoGgj2EkZoqVyRPOTQQ==,iv:zlxa0ivKw7MA+8LpBKGYsqwpUnmE3NdLWeXs6H6m3T4=,tag:0ZiOk1QEWuSmQAEHKw0CpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cg8jk89nugmrn3rylak4shyaq2ssgvp2g6975884zp3u2t8klenqx9cnau
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaME9kV0VnK25lRDhhclF4
            SE9PVHVxVlF2aE9PemRYaEs0VVhMT0o3WENzClBPM1BRN2p6WXRvWTFENWJudW1v
            YWI1NlBkTjRoOGNsN3ZnSmNZak15QkkKLS0tIGZFeXdzMjhVMnRDdVV6akRYLzh1
            eWl6WU5odUk3SUdBOWdIWGIrL0dMOGMK0NdE0JbAIPkRXtS8+b+lQfLlqwQZFge0
            hRz/ojovN7KJtfG+Z1TJ9YUNMZOonulp6joZdFxIxm5D0keBBjsCEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T15:42:34Z"
    mac: ENC[AES256_GCM,data:OhUp9RbfpYg56oUJC2XP40zOFSpozNh7pHm6S+te0lKvmAJQHorW+9I9f4fitBvCnwf/Y5e7M6keZIY3xR6Zs52dsQY9LgLNWGqFzMdmJ7kvW44XxK1C43yCP3IKSWgBT+i9JAgghcIf2/MFyB8OahqusgYPaA2Sed2u7CJg7hM=,iv:VipU+pTXFSmaq0TneEACtCqAG5HSS/f1N5ikxrIFITA=,tag:w6Gxqgt4jQNHze4ZoCIg9A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
