---
kubernetes:
  children:
    master:
      hosts:
        k8s-master0-titan3:
          ansible_host: 192.168.9.131
        k8s-master1-titan3:
          ansible_host: 192.168.9.132
        k8s-master2-titan3:
          ansible_host: 192.168.9.133
    worker:
      hosts:
        k8s-extensions-titan3:
          ansible_host: 192.168.9.134
        k8s-extension0-titan3:
          ansible_host: 192.168.9.135
        k8s-extension1-titan3:
          ansible_host: 192.168.9.136
        k8s-extension2-titan3:
          ansible_host: 192.168.9.137
        k8s-extension3-titan3:
          ansible_host: 192.168.9.138
        k8s-extension4-titan3:
          ansible_host: 192.168.9.139
