# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:n1wZ25whzoZ1rVRIaHOcv6sEWGXZ,iv:06ZPfgP2PYKmQWHxLKKP2yCyVJ9GbKSfmmFi1pxlc7Q=,tag:/TSyQYsy5t+g7SAaBD3MRQ==,type:str]
    api-key: ENC[AES256_GCM,data:Fzl1KVZ4f+FLqd72x5wKVHHcwXX0CGNPYo+V/wpdvRryBwvJWQ==,iv:1pg9p5PhaRwSv/jUdDzyGQVEILN0C6Batp2/BCC5WI8=,tag:SWk8ehlZLMOkb17nmoGJJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cg8jk89nugmrn3rylak4shyaq2ssgvp2g6975884zp3u2t8klenqx9cnau
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdFNqeXhBZmluYjk2RnZF
            M1ViZGJhUGVQdFp5V3FJS2c3enFrYlVOWW5vCmU1UXp2cndMWk5CTm1ZT3h3Vlp2
            OWJrbEFiclk0aDh6ejNCWnVCY1NDSHMKLS0tIG10L1NCSDR1MVNaZzVKRkhrd1lZ
            aFA5bnRMQVgvL2I2SHU2Vm5FRTQ1UEUKvD6bt+awutZ4/j4J82G6/gzFr2vnFOOX
            TkpTbnchgLhWuDDLKgEwzKGStrNd74Nk4lgb8/XSC3WuO/t2IXTxxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T18:09:22Z"
    mac: ENC[AES256_GCM,data:Id26BtSrpvY/ttIX6zVU84HAlLBL/oTCy99E+CznOFVi5o/QceZhd01EwepzzpqxMZpiCUKSgxrKc9d6Vmc1OnmrYbIjosJRNtbCrq/blKEzEIXwaxp6SfEwXl+rFW4bGUVyimHuJBuzT2oCYbxV728qeSaS88AKGf3oboBeCWA=,iv:cK3es8u1UX3M5vNK/ubq43M5Hl3pejQcqxh9D8efHKU=,tag:+47DlK9gTcDy8uzd47IX+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
