kind: Secret
ansible_user: ENC[AES256_GCM,data:SEmyUg==,iv:vbUZjD2+s1bX4S2sBFHSElMmuIx/6GcHhTaia7/fpk8=,tag:UrF/363UfCQGcyb5wAmekg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:7Qf7Iu+MOVEo2hX7nS2o4R44GObV,iv:TPUs76Yq6TotJocA+8WO/5V0hvjdV8I/bDltDm8fytY=,tag:EWr8+ZOVjmTrAlfeoPVlqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cg8jk89nugmrn3rylak4shyaq2ssgvp2g6975884zp3u2t8klenqx9cnau
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRzM5UjljNXJJdXc5UlI4
            c01lOEJpYnFsdGo2MlhqOElmUW4rYmxjTkFnClM2VmZzb0tzaVBJalhjZHo2SlVx
            Y1JNYzhMWFh4OEZCdUF3ZjQ5M20wazQKLS0tIGtUUkxKNi9YdnY4c1pXRG5XZGlH
            eXBLc0lHMFZJZHpwNkFNVUFraWtWdkEKSSKEc2ToRNMPQBxER4gpu0gDRJ3b8NIh
            moQnY2y4sSl65TDCFI9ueFaCpXGtHAcQD+66BH8/uGW2ltZm824pxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T19:05:12Z"
    mac: ENC[AES256_GCM,data:JhCJMwvblV31+wn9O8OF7yzguceKD+yoRTRqirgFZUEBFocwuu8cWcjf15caZV6s7l6QAtlyZcLxAWCIPfUXTGdefN2UiocLbS3gejKrWEcmvn7w38bCc+bTouN5oZHpxJ+VWin8UTES7ju/NqtbITo3ge6IxtjCoqLeDTfMDn4=,iv:BCRBfWVzz8cpZctRs6Jc2qnSNuwtuI2rOQl8ZXEaMDc=,tag:D/yL44pAUfbBGdTmn0RNrw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
