kind: Secret
ansible_user: ENC[AES256_GCM,data:luBVqw==,iv:QCZbmfmIJc/c5LBI/3rB9jBbVhSgjhG++3lscdYjf48=,tag:nBAiUChesJTERgrEoJ0Hog==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:pzNCptphk+Bxea4rIbVIkdtJpD50,iv:H7rBsk9sqvwDdV8ZDniquvMlUqn/0HJM/fW6beQi26Y=,tag:UOLbhyNbw6VGqdUT89vR4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cg8jk89nugmrn3rylak4shyaq2ssgvp2g6975884zp3u2t8klenqx9cnau
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsK2lnM0NCZm50MlJIV0ts
            MmhkMFFEZnprUWtSTCsyOEh2QmdUUXZ6MXhFClE5WTBVcG5Mb3l4SSsrS3VVM2tU
            L2psMUJHRjZ2LzJXRW5pK0hrZE9INXcKLS0tIERVZklIWllrWjR0SHJKcUtWWlB2
            ZTJjVU5qY2dyeHpaYmp4bVV2L1ovZzQKiq0HBvmXd1PTwZd10tXsrcZNNMvIBBaf
            vNsfwhbJ4U69aMr1xRPHg1ZwAzCeqb3jFEPKlaz8VfJwb22jKWqfkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T15:42:34Z"
    mac: ENC[AES256_GCM,data:eHz2ydxzv/CM94cJRJY2Tu9+oXcnf1HSFoJy6MKbrikdvUUJMEdPDrt7lj9MegMBuj2pCKq3RfYr7leIRPez8DV5VGuR8dLCXKq3fhYVDDdlKda7bTTCUJZs3drDW0ONxAdu03JZcrqbf0dfAOU/9NRn7pOh6oclUxSTMjeRaVA=,iv:00vBFDZzLbYQvp/IKjHvV3qWqcBhjGESYnnD6B5BH74=,tag:ATKuICz4D45bPu8VnDzzhg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
