kind: Secret
ansible_user: ENC[AES256_GCM,data:puZYEA==,iv:E2GPEz9t5O8kZCNFqiWt62ZIUjex1UP6ZmRgiMZgKGE=,tag:BhHMuEZHuNxBtIbq7KXOrg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:QZBw4jUhQ81ohJz2ocgSakMNnOoQ,iv:T/FG07dv+xD0C/haJIuqbOHO2cQcUqs03L3k1EHRDu0=,tag:mNn7M0r7MVJY8EbXm3cmYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cg8jk89nugmrn3rylak4shyaq2ssgvp2g6975884zp3u2t8klenqx9cnau
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2U013T3F2Z0VlekpjbVdQ
            YWlqWWFONjIrLzFVelRqWlAreWFkUXpib1hzCi9ZNG1yWXpQcUp6VEpiaE01R1hk
            dlVDRjBTT2ZBOW1tUDVYenQ5cllKeU0KLS0tIFpTZHM0K2dKVnEybGlKL2FBSmxT
            VlZIZm1tZmF0Y1FHbHdDejBsY0QzUmsKQ29gBomIMrhxZ4/0bHCiuTt1khICK4pk
            PCFh5Zlw7zAHWAI2f4gAM47y36m7miCO9vEusxOMQI5ga6W/rgNUXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T15:06:12Z"
    mac: ENC[AES256_GCM,data:0c7IYa4jGLy0oe3TbhcyhuEQ6vxMAnB3X/DAJSFTyqaWj25zLZf72XAqq5XFSqM49PQ/w3SNz8xd6anj12RYb4k1SOsv4pxQ0ZlbNJ+iJAMu2heNAubNn84DA9P6lUSY/7cl98sROMqm1zKR62tZ2VY4R8BrlF5ohdcy/9jWK8k=,iv:usZseV5a841o0X7ru7tUFdJ/hnbvgCTt4A5azL8nh6U=,tag:I0zwPuQcuOcB6/eU0bRpLQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
