kind: Secret
ansible_user: ENC[AES256_GCM,data:Ts3XbQ==,iv:2e9mi0OWUkCXTGpDlhkk+fTyxZeXpOCv2y4gs9w4wL8=,tag:2HykOf1XomORRlJVirn20w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:aRZhZ9Fib8oPKuQ3TV1mNN02yXK2,iv:3reoX+2+d2JrjSx1p/bcJfS6QF+dW0oCYLfj9KyEDhg=,tag:nECr7NrBQLcpumu2MQn1NQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cg8jk89nugmrn3rylak4shyaq2ssgvp2g6975884zp3u2t8klenqx9cnau
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmQWx5Z25oOFI4R3oyMDJD
            M1pwMWV4N3I3Q0JOVUVBQnlpb0FvZlpkdjNZCkVZTG83S2Q0U0dXTThlN3NjTE5i
            aFhhV21zTlZzN21iN3EvY1lXUDErdGMKLS0tIGRpYzRieVh1UWF5NkpsL3ZPWnBB
            ZnUwazQvdDV2R1hJL0FHN0pGVlpOc2cKFmzPR41k9Lc59w9sK6xBlvxnzkU2UQWY
            jQR+61PcEBKKETbYlM+P/rrASDNhVseBsQMs7fAiBjXP/0Cwpux00Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T06:55:19Z"
    mac: ENC[AES256_GCM,data:dF08zcyQKd3pfDkFy8QWY1lmVsgBf8eu3YU1vhuIWLTvHPBM1wGyvihhlmGGtD1zz8ucWOw+q1eyK3PKimC8uHj3gQS5nJjx1g/EVG3v+jk+vdUW3wpcnTkpRvBKGPWE1I8u9SvEe2Esu3ikvKSBZLOsGtZYfr1jJwtuN6lzUXI=,iv:bf/oe1JtDck+8fzK0Yyw+8/NputX8vG+pAJPIlZtwvw=,tag:sAu3va2Jt88r0sgMAaqJfA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
