kind: Secret
ansible_user: ENC[AES256_GCM,data:4Yi/MA==,iv:YAb5YIyBJFxREDVDhyTdCj0v73i3Ta6I9476GIHGuJM=,tag:IyPOT69XGNa9Vtk7EMjH0A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:rhZeEjpJHwagjmrDWN7R+zzfnCCu,iv:hroHVWylJTx396f3hTHQDPzyEQTfZXFpbjOeXHIizsA=,tag:ai6jjsbOC8v/kvEyWkGusQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cg8jk89nugmrn3rylak4shyaq2ssgvp2g6975884zp3u2t8klenqx9cnau
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MnNNVzNRTHNFVVFONUFi
            a3RTM0NJdW4zaFlnZ3ZzaVo1NThEUnVITGc4Cnl2NFk0Vzc3czJYdTNZbVNjYUw4
            R2pJUmZBWWVrR2d5SDBEbERWekNseG8KLS0tIDdFVUd4bzRSU2hBU29VS3I2UkJS
            U3cxY1V0TG8xeDd0OXcvL2FRS1pnc0UKagoFDQgpzB300KKUFRS/U7naKj+6ZUqb
            zdtH232OFP/EyHLU6iIDVpWuy+sGxJRRSiT8buuf3l3ypOVNSEezmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-15T00:49:49Z"
    mac: ENC[AES256_GCM,data:O6J2zRqzt27seHMqLn7AMl/irQRVokx2mrXaqbJqBi1qhCjestVHaTEhq1j9b6k+PGYoH6pyHeKt1LEtW3RMlwDghp46I/yray5PT0tvnCv1Ogarffet7gq76Eb4+sZPty85kOPHThQrFvBncJgdFki9ujePeR3/UjcbEprUrBM=,iv:Lx+3U8vrQUeLUCiDByqM0kH9gpOyHu5JI0otClr4WRE=,tag:YO1bSj/nZcqKh7uruVTQYA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
