kind: Secret
ansible_user: ENC[AES256_GCM,data:ABz8ZA==,iv:CJYxW6rsmFeuJbPlk89z5gksPrTBiehialm01o88NTk=,tag:qSpioHCnefrV5hDC3t7MrA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:tajjM8cGNuZ78FoPYKsmyeLM+Tnf,iv:MrcXn6MAcLli01XtsgJtMVaqHTc2Sa8zmZp0nUe2NXk=,tag:3xyTl1ZRusHE5oAY9QSoUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cg8jk89nugmrn3rylak4shyaq2ssgvp2g6975884zp3u2t8klenqx9cnau
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZlVDdlFJR1kzVmVXVGxi
            LzVLYWVxdGdlTmJhVTBuNjgrL1dxY2g5WUY0CldwN0Z2NHhJMzhLbFV2cTBMd3R5
            YjBHU0NvaUJSeUp0cS92dmlPUEljZ2cKLS0tIEtxYWMxZ3FLTXNhVWd3bXZoc21G
            cHFaeEQ0aHg3SkZOUHU1RDhNZ2pmeDAKU8dee6OyHJS/80XQnxyRmZLhP6ZvK49D
            g/iViMFvOvyAaW7HG70JDEUACc2ew+Sr+fEgHhiZf/DjCCnzuw9asQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T18:09:22Z"
    mac: ENC[AES256_GCM,data:MRvE0KSguBtoAfQxbrV0bkaUFU1tQ5DUgLCNXDVGajalpOH9URC/P7YX716RH8XWPftJ+wAlGebPbj8KlkjXVMFW/pmoud87oUb/MlIhKk8MXauj78BCAPyuPqGYhz/Y8ZekngJhEUoTuJFh3uAvvZy32MBFCwI2IqaGFT3djI8=,iv:2GFETyDem3CFgEnVKhIn4S4Z21hPj7HZ/7dcUSymJws=,tag:Gi1b8q6vzWH5r+FKlOXrHw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
