kind: Secret
ansible_user: ENC[AES256_GCM,data:EYWnLw==,iv:vAAqJ3Zf4SY25amZrJka6bkhFvrEfZ8K0QNA/wHB5JY=,tag:20ApqRqDYJjzya6mv5FT/w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:jVA13S46H1qAY5DL8oWwECMcnqdy,iv:xg/EAfwa+ATYXI1jAIrRYW7S0nn+zZOvWQixwF/hoU0=,tag:qXCcw7n29oLwl7GP252Bww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cg8jk89nugmrn3rylak4shyaq2ssgvp2g6975884zp3u2t8klenqx9cnau
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPM1lmS2s0bUdzS3hub3hL
            S0ZmajgrSTh5UlVVUXJVQzhyTDlHSk42bUNVCk9pNkJjZTFHWVNoK25tMFZsUlpN
            Rit4OXI4OHBUZFR6RENEaGRBZzMrVWcKLS0tIDM5TDVkSk93THNNUW5vYXFMZE5q
            SHEwZE5EWGlXWmw3WXRJTGsyWmdWdWsKVfBYO9VQU2HHqAZ02FcvduxgUnv0/70Q
            +IWnFwJF30WqFIsTc0jWzrbh7mlaKwhuXmwTfh24ek2JEnXfkNzzqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-15T00:49:49Z"
    mac: ENC[AES256_GCM,data:hm7V4FFLA6QQNiiy8KZxe5SAXmqzJgdNxttp0j8uFDIcJ4lFaZiMkmOgLszLbXFVCE8OpUZZGa5/8fM2UMB1Js2QIKYJJ6MY2ssi+vbpTRe0bwd+JkCiSL2QKnFOLholI/sWEo68otYaEcOOzsA2dwjlu/ZrRlATzd2dlP3BWzE=,iv:+IcOqut7ukfDHakN10VNePTTKnRRcgZuUPQ8Mfud17w=,tag:Qam9xagd30fwQCGz5WnU0Q==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
