kind: Secret
ansible_user: ENC[AES256_GCM,data:gJLYtQ==,iv:wXyJTYzzbYty3CnUq1LyrmDdIXFYixwSi63j/KVlyWo=,tag:WmFYfNyH9p6tSwlT0iNe6g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:6WdbRHnddcuAlYC7+WMDzEqZA7yc,iv:LyYbmeDuwMx8nw8wyalJh+rTTQibnrDxpq69TJbNMMk=,tag:AJVsz4hBBQ/U7HNVgvseLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cg8jk89nugmrn3rylak4shyaq2ssgvp2g6975884zp3u2t8klenqx9cnau
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxd0hkbFhyUTdHM1hENjBy
            V1JYbW1NTDhPWnNPV0NBM2R0aHZFQVRNVGw4CkR2ZXUxWXI3WUNKZ1lJKytkQzJG
            UWtSbUh3cFNJQldUY1dxM3dzMlhLQjQKLS0tIEdQa1pLVXdOY1c3UnBrUXh3Y28x
            SmFDNTR3RC9BWStjbGtzUXEvY0o5ZXMKYvwyPRxGbFCp4xuG9QPSntyBGczWFQRJ
            v7aB2VZhQNDR6Qs6JybvlYp88MVVt5hjO1hiHOk2txSlEpU1bvOHsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T14:11:23Z"
    mac: ENC[AES256_GCM,data:n2k4OywPbOEBwbTYzCCy5LT2hzaZjN/9x/kgQWzv/wNIkeQG8VKzvAJmHlFCEo88S6HBsjmyG3YBIX8bK7PZPRHdfpYinxJTazje+X0/2GJS0J6N/Qha9YoR75kg7r3HeOx4JZvrLjAJ42m7iZCdh4ACBTeyh9x1BUvZYoYpqkU=,iv:VkYwD6X2z3UTD/CpH7ZG0Zd+Tj7oK4Pu2J5E/x5tk5A=,tag:gCDOhETSJdBm/s4uKnE6OQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
