kind: Secret
ansible_user: ENC[AES256_GCM,data:a0WgKA==,iv:GZkcvobnQTQQa+jBfUW6Nk/ROgxuDlrRw24yGNalhsQ=,tag:azCNgw39KeMcmmtikvyGMg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:9AQm2H1V16f8e/n2c8gcjJ/aDue3,iv:w2zuddylcrZwApgoZDNKo3DnzHqYiTeJer/Q35w+LW0=,tag:aa90yJx0w13AprOraqREdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cg8jk89nugmrn3rylak4shyaq2ssgvp2g6975884zp3u2t8klenqx9cnau
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUFJtdHlMOERET1M3Rzlt
            U3JCMlVYQnNWcEY3cU9KcnlJOFEwL1hCQ1VZCkpvUDlHZmJ4SEoxTDR6aElHdVVW
            YUJGUVRyVzdMZEtMcGxLaDE4QjVGN1kKLS0tIEo3TVdSVTFLR2hITSthcUJzZTFy
            WFJnbmFlaTFKRE8rbmVKSUd0WGlFSjAK9QaLdKvTLPVJ8JWp2VsDnh8fxgn8Z8vB
            rHAeqBmcFXQ4TVzFTdO99FrKK3sWlOiTGj6yHuRRrNHS0W6j7R9Sqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T15:06:12Z"
    mac: ENC[AES256_GCM,data:rKJinlXGF1gZnmioU529e2yFiz3EOanjxAFCKShaNsa0PvpXt4YxibU2xAMvNSUJJVNL1NDQfS3Z53m1EsPjbjq9lzb3NKwstoXAwYg74fmPt/JvUrwjFjhzjNXxLjLP5LgeKlf8BLk8RRiUT/tD+iNab+ITcW+Ewx/H/gs73/Q=,iv:mg7beHM2qW59x3VTY2cBt82om9NUYfrVr/yrEkK0OT8=,tag:V9AdTHJoYufwoq5QFbzjbw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
