kind: Secret
ansible_user: ENC[AES256_GCM,data:I02uJw==,iv:HxK0J5KiiRngtgTICYXVU0LrMOR70AojfEFtj+8aG2s=,tag:odHrfNY/PnGpqbvFhV8r+w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:mSqVT5U3p3bQKaUCibfk8GJRUL7Z,iv:qHO57BnAdUY/2f2iaR6Hbw2uMLKld0Zasyzn7kgbwek=,tag:cRTgiCVyycab50QIJv0dgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cg8jk89nugmrn3rylak4shyaq2ssgvp2g6975884zp3u2t8klenqx9cnau
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aXBRRXprSXR2UEpQNzZx
            clFybWVVNktOdWRzbG5mZUk4djFoVytyQ1U4ClJQWVovTVpKSjdoWS9JeU5MNXhY
            NVN5UkduQ09oaTUxNmxqNEphZUdaZUkKLS0tIGJBMHIxT3BQeU9SSE9GczA1Sk5L
            ek5LVUZnVXhwVmhXcndSNHVTeDNXOHcKxtXvA5WplkIQFE44JW9v0PSza/Bo5tOC
            gt2KKjQ0KQ8JUFM50tgLAmas+v9+6FE/QoWrVyEQh4vYf4G0QCjscg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T15:06:12Z"
    mac: ENC[AES256_GCM,data:pFaU2405s1fXiENHDIHrOHbNLXj6r089MmEaqXSOUXkUGONm9UK+3IduJ54lNTh2TkJtwrR3tCJdqBhtHWxX9GuTmt31C7hNx1ezpwaOqO3VwEQZU93QdKfCgUNMUZExeRQYMVymQ7D21YEcsazMG2HdbE+/OrXv5/xgKYsuLQ0=,iv:0n64gMr/BWWUjFRgax8+JKKnmkxx+oSmwpkGtJJwrD0=,tag:aYeP3jKlnB2cpN9PoiHq1A==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
