kind: Secret
ansible_user: ENC[AES256_GCM,data:7lDTFQ==,iv:N7YORftxSjRBuwfGWcZMBD7wKpsTBsIIwI2zOof8Wq8=,tag:ocBbgxjn5x+6jfO4lKAN/w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:5XYtutSD/SXrTan0vXWxFwl1Z2jw,iv:HKJ5lmrSdRZAUGqW7eQKsreN0CTd5OfZcX6Iu/6GhBk=,tag:pfv+Kw6jmo7edjTc23Qs1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cg8jk89nugmrn3rylak4shyaq2ssgvp2g6975884zp3u2t8klenqx9cnau
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwOUdCUjJYSzB1YnI5SmRw
            K2NHYy9MdndiTCtYVjc2WnhZTnN0bkJSbjE0Ckt0VjVWeVZpeCtLcCtTcHplWlds
            cDBHb1haQThzNm1IR2EvaVlJWlBYcDQKLS0tIDgrNVZPREE5Wk1FVG1ZcDRVMGx4
            bUJTaTljaHRXaUZ2K2Z1eFVNOWZEY3MK7lrC5omv6jY4xKbfNofw+tBSSDD98aZ1
            RLXbXRCkvnZOcLFYY9KMA+jFOu0BZW6Fo1P6WUqX1kU3ZGcGjiXBbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T19:05:12Z"
    mac: ENC[AES256_GCM,data:bSrpycQESr9ZLt9mzlsDuHeHvHGpOJBuC5Owp/NLKsr99i7t0G9UYPSeN8GUdflgkc911lQPLf8+V16WIWEgrtAGZXLGeAj+JabZpzxYUshMxmmINE3hoNrUwMy3Ku+23sDZsPpsHgzNY44GhYLiU6IkxIP0/HxaFXyeOw2Z7Do=,iv:wS5+YBT0330UUQrlmfiVRvE34cZ+qCM37GrWYGVqShI=,tag:c+pek2P5I2ntdvYENsW0Dg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
