kind: Secret
ansible_user: ENC[AES256_GCM,data:OkWDFQ==,iv:PiNvZXO27zZwZgX5sRBFD1OmAmeP+eJoMVROKTKq6fw=,tag:48x9uzxrNzbobH3kOzjoUg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:4XlGUK/NUwAegBTB/48wmTQBYWrp,iv:qAZnmwG0rSOx5tymM+74C1ZG3yh1XJAdcTCVZA/GWxM=,tag:V9jew7/f1ewFyD3atLQCLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cg8jk89nugmrn3rylak4shyaq2ssgvp2g6975884zp3u2t8klenqx9cnau
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZklvbXAwUURIWkdnTURE
            VElQQkhlZGxQSHZyYkFqeklxcXB1aDh1VVhrCnVhNk40bUVQMDBwTExrRnp1OHo1
            NFFhM3BYb09tck0yQlV5Q0JBUXdYNzQKLS0tIGRrNWNVei9aVlpGeU1yVUttS3Nh
            Zjd5N1VXRThaYldEczJDMmZoMkp4MU0KEhYIiiWpfHjvl21bzNS4gyF5aV4xDnD4
            wcnIZc9ApQyxEUiGkCa7DVpnMkPmqwNo3pRzH+PZskegVc/M5eYtwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T19:05:12Z"
    mac: ENC[AES256_GCM,data:DOJz89hQbkZ4z/aYYl5pxVCuKXVl/JT/oeArdEWsJhS/UVqR0omKYV1j8GdMy9vKLLFmFp82tNpR9IyjqgolEujqxYGjzD9OfF1uUJkaza/8v7JeUcIgd7B3tBCM48V5bltJoZpqHYeODAwLGzabHL0kPZUC4695BcUQFzNcfeI=,iv:5jiDy7lsBZsmitaYqEAfs73VaZLevGrd3RWLvcTLFc4=,tag:FPow23w+1AgVs5PomdzeMQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
