kind: Secret
ansible_user: ENC[AES256_GCM,data:IKpVhA==,iv:3vnQXY63U6GVmrHeWVOhb/A+FiLBKKe833/uQXcJ7WQ=,tag:hgONge2GSm094BKmhp8Apw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:6LQ+2xrp7Gq0KyBFMNBcWGTahirK,iv:4FDPVD3YnJvwOcziJ//e0BtpdGfYMhnI7JKEgyYg9AQ=,tag:bG8swjzQie8m0kqV5ZM/OQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cg8jk89nugmrn3rylak4shyaq2ssgvp2g6975884zp3u2t8klenqx9cnau
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQVRNS1NKNHNxbCtyb1Vv
            b29yRHVpQi9scGphcXZ6ZkhtRHZuOUJqQVQ0ClZHbCtNam45N1U2YU03eGs2aWM4
            eWxGQXArM01OdjZXNGhWMllMcmJwbXMKLS0tIExVZVV5TU9NRENBRTZJY3VBT1RT
            YzF4UTlOcEpEa0EydmhoRVE5ZFcvK28KYPJHDb2SpYDef7d8NaWyDfp+ZFF9liTI
            lksX3XgNuQNelOoXs4bbVNdYvdtXiWq1WoyhgS53zty4WUIXUPqpnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T14:11:23Z"
    mac: ENC[AES256_GCM,data:qA18Mi3zUwBzCpnSm4zALnT2yc4QujNwgc2/34n4uqjMpGXi9kkvF3mnBHk9VlKVcdFQnBIfDrZGOvB4FKtpthYnCH41gdnnp3u5VUSRHYncjsVXmq17mLvVqpXsG0koK7BdGZAYzbG6w7ZwrYNgIt426qjdKEkGUJ8buzcz9lw=,iv:wywh3P4FYYK6LomjqqU+D3iCC3ggkIOLbPX251CNvHo=,tag:pmbDSKcFQkzdZUZh76fFRg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
