kind: Secret
ansible_user: ENC[AES256_GCM,data:aa0Sxw==,iv:v654TA8/UKGY22NdkSs3s8cMvzs/6lHOPMH7b0JvqIw=,tag:vyQUTotMff+i2hVGXPBzsQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:puv/mi1MX6mFMflmO4y0OOngAP+w,iv:jA01i0MtfW0cJiugT7YYb8GHUei8gqVN4YSf8wttnJ4=,tag:6zOpMKDhwAyilgjwtCP4fw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cg8jk89nugmrn3rylak4shyaq2ssgvp2g6975884zp3u2t8klenqx9cnau
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4anRjQVFlY09zQXZ0WUlI
            a0d3cHUySmU3eUJwTnpvUGIxRkhBaTVHVWpJCkVkWHFSWVgwcVMrYWtKNkJ0LzBT
            OU9ndFZIRDg5dGJOWTNwTlhnRXlJZWMKLS0tIFlSTSs1T2syREs4M1hJUHczMnIz
            eVhqZWtZS0d3elNrRUcwakZ6MGVCajAKUobZuXNTQQwn0C4t825wNLDGue0UUROP
            8sDfAMkQe0G6KnVBHfWlCJ1EnHDaDT34EZE9mFj98w7CsqzlJCT6XA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T15:42:34Z"
    mac: ENC[AES256_GCM,data:nmFcLZY6Y4/sXxtPblnrqYXuksJHbUckDqHJJT08+C8H0Q5mR7MwQlQ2smZOU1WkyrL2C+4Ak2Rt+w2aToMm0r094RWBA4BjOYJRCsrTqMCEfVcLEqFmGINJNum35StsGhqddj5tFd/UtLM/TXaHaOpw+pSrXXuY3m3UNmAJc9M=,iv:GmxksJ5s6b1aAD59q2heskmraWeGhy0LIoi7PqECKOU=,tag:HcjSdHGeh5pXlAGSyQP+iQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
