kind: Secret
ansible_user: ENC[AES256_GCM,data:m6FqWQ==,iv:kzAehD3VoTPNXyfOkmngc245a7392xWRxHUHfdd7AWE=,tag:twX8aTITAGLJFypZzI2nbg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:4wgEReay4+jASCo511sNsJiLKbLy,iv:yQdVQLokVjwi+TubkC/HEEnyoYfgSJivbCVhtTINAE0=,tag:dcnS7QMu88xim1/8c1b/Xg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cg8jk89nugmrn3rylak4shyaq2ssgvp2g6975884zp3u2t8klenqx9cnau
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArOG5GUVFUc0QzWXh4bWdk
            SkNOaGhzS1ppckhRczQ3cE13cVJ2UXFHbVM4Ck5qNzBxWUdzSWhrOWNGZ0ZQUk5N
            L1Q4elBNcE1CZ3ZPZDVBUTVkYVRvNkEKLS0tIFZPUUFNNEVsVWhxeGZSZFdBWGo0
            VzU5UmRyK1FMRUx0YXVCbEFiUE5xTjQKRwRHA3LzdQap2dUhgSm3XcJjz4PziXLJ
            hHJHiCweGYL6f+4eF5IyLbT0njfrzp3PYJaPapoYO495d+IT2QxwBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T19:05:12Z"
    mac: ENC[AES256_GCM,data:+0if+1VJK4A3y2tf6URwUoJtadS1BwaXBSHO5ikyrtSE4F3AcJn6LAOpy+Nj/YyfsdIjS8hz7sGqZkgDgZX2sLlBtL4lmBTgXzAB7y7ljQaWfgkZPl+OtfulvY//yTOzJzncZtVDsICbtbhozisiv7m6jpQXnUkb9nH1PH5LBjk=,iv:s8/2JsLHNCoMl1M4SRdJOWXqKzfIPoygCsWraEgVVBI=,tag:FjNAv5qPwl++WnlmwAflEw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
