kind: Secret
ansible_user: ENC[AES256_GCM,data:pQSSdA==,iv:S8v9H4tXClX11auL29NIzagupIhNbkvUmvBwJAo43y4=,tag:4QBoLoKyFOtRs0Pc7I0buw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Mv+UghvKk75gMfxBRCaaSltJ84Lv,iv:ruqD+G46HhNx1XzwFfgcka2UqILG6A1t09PElk1Nxf0=,tag:fgpcsXBEXiR5PJEwbXDVWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cg8jk89nugmrn3rylak4shyaq2ssgvp2g6975884zp3u2t8klenqx9cnau
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TWlldTdueVdaUFZSTlA3
            MnRiZzJhb3pOdTV4dnJKUkxnVk9WdGxBaENBCmplZnBKOW10OFdUQTFhYTI0RWhV
            TEpGS1JDaDVROUdEYjgzbXpUYm5zcmMKLS0tIDFTNXNMZjl6RWh1V1pzRWxEd1FW
            SkpSejlqRFlJdnNBZ0hsSVB2RkNFdUkK68VPmAAw3RbH0Kt2BdQhLFKBPAM+m1lM
            EPWgiZo0DgZIG6K5IH87qhk6FTv8/IZgfjud2AKP6T6rxhfdwgavWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T18:09:22Z"
    mac: ENC[AES256_GCM,data:c2s/YkBaecEiU3HpELosqEsw3vochLpdzzJhAxrgshDWflbIpOmNiNepFNocnwhyDRAdv2FtBalApybgRAdznnj2fqZUTnztuzQsLqA5z89x8/esRXdBv3b6o/SqDUKOtxLfIjLU1qkIPF3Qv/Vx9YAfq9fwyWza5cX8+IJbqMY=,iv:FHOafPHZ4q7zRGIHFkHzMDYY7WF11O7VE2zA2SMkL9s=,tag:uVneccCiMJkfa7eA1Rs+yA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
