---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Denver
  METALLB_LB_RANGE: 192.168.9.100-192.168.9.120
  METALLB_K8S_GATEWAY_ADDR: 192.168.9.110
  DEFAULT_TIMEZONE: "America/Denver"
  LDAP_BASE_DN: "dc=mdlad.esones0,dc=com"
  SVC_NAS_ADDR: "192.168.0.6"
  SVC_PLEX_ADDR: "192.168.1.9"
  SVC_UNIFI_ADDR: "192.168.1.1"
  GATEWAY_ADDR: ""
  LB_NGINX_ADDR: "192.168.9.106"
  LB_TRAEFIK_ADDR: "192.168.9.105"
  LB_LDAP_ADDR: "192.168.9.108"
  LB_REDIS_ADDR: "192.168.9.107"
  LB_RABBITMQ_ADDR: "192.168.9.120"
  LB_POSTGRES_ADDR: "192.168.9.119"
  LB_MSSQL_ADDR: "192.168.9.118"
  LB_SMTP4DEV_ADDR: "192.168.9.117"
