apiVersion: v1
kind: Secret
metadata:
    name: harbor-config
    namespace: dev
stringData:
    #ENC[AES256_GCM,data:BUzzLGt/9kPDLurq79m5GGl+AR8a8DdTQlmXR+9WgI1iKovlJvNs4mEd/CuFaQnNBgMVJBl0yTe1uxXMPXVdoeYSYRV34OHDISH17bdCGnvkMeuiIYD7qo9AqjLQ8XUhvkAskK0LsseOg3INO9JJ+MLAOCmGYxDqDcm5c0LA7MN0sngRYGrJrE5GzIyX37NXDtjI/xvJ0e8=,iv:OxZOrn0xW3T5ARvzqkOI6Iof5IuOd7mqEDRcft+sK0g=,tag:sP53CVY6uZp5vyFjMZlTPQ==,type:comment]
    CONFIG_OVERWRITE_JSON: ENC[AES256_GCM,data:Hw+IUkx6V/0zkNrAVq/7a7F6AmZTBZJemTgqTLoqrZKtGcHjqx8xuaWNGoDBpZxgk4LWjrDJWXT1FuiffldDAFFeCJv+Qly32fDuyskOse6XdYCbDBDGQjqzSfZBY8fIAeaLlsLSYjK4flEdrisDJoZaZQbrU3/u7Del5WElkRRwWPI4VXgjELsRH8P/EteuLVGMLJfdLgRALcCXcaffgCuMa0x6ZLpPVaZtarrDgdO1kmswhgOY5C8L5htCcQthxh5sK6JqJt1f9fUb4+hhxt9cO3qEjdcR9nxY8sksk7pa2g3nUnSb1z+LGSKuZKMfjU5l9ixv0/euNhzfVaX9y8Om5nkz85Oy+lRaUy4scTkJ4RK/HtvozZevU/KIOIMXS8G77h2DljRB5UmtWrYfLqO0hVdTG8t+c6Ol2/8JpRroWu1Ge4F/fqUWUvCBmj7nQwNvVrnP26EXD+Bjp4yl4027Mu6Q4dJk2Y4SuVt4DSvh4+yzKD0ZTAru3DGQtfGiZFh5oi91K5iK2mOs6FOZYPFvf+xiQvqTGIPp4AWFdP8umjlWBvX/h6clSi6ZSUHa0fKWq6Py/tWiV6fhYF9c/Pdzxo1IevzaOcqv/n54eHrvBaTckFrD8e2lnzOTflBhq/FDY5ZDCAu+Q/GgAB0AIQizZN4mwwss+lNB8u9HHOHPuCbDKaHmE60CywAebG6023EL93WperWuY2FRjCS35vEfiB7xGOcKNUW1H/R+qE95qNC7CzesFx8/DxJuAF+M/odedKHTv7ly1/xYhFa7ztZCRJvrSJ6u8cRWu+2rwxHhOGtw5IeSoKjAcj1R130fLbjwMPEYTyDc8h1Agkn8mZnxg8E7HkyEtRxTk/atpeDUqYYy2S5bUA6Jc/qOIbJ37fxqK4mXSu+MPEa1uOQGDMqek4jCREwsNGnKmI3Zo7fDWrtkqB0Hv6vPoanSX1gXDy0lJC21HFKGNkTNwpGiUDo2bJoVYK1KKyJZTdqtDuwN5W1aKUbfcfmbomKyrfVMlScGg7WhlmK28LSil7sq2FV8GmqXoqSyZJ1oKGAMazYIbbkwWLdpkP3QUAABkslfcv4hw8edXuIP4Rh07CfR41GMfW0p1k2x1FYWHoag70Kqz53fA3rbQUmZ4FtYUPNMYe52cavkNw==,iv:xhIRjxCy8nS5O0zMeA5+EwPj36wLrr2XcBoZzO78p+c=,tag:C0IT/AGr9Wkq8NxRNhrF0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cg8jk89nugmrn3rylak4shyaq2ssgvp2g6975884zp3u2t8klenqx9cnau
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFeWdLSVVmQjlkM2JCdXY0
            S3oyMHhEV3h2SFhJVmJTb0N0L1puL0pMQld3CnkzK094NnhPWjZIM3kyZUUxc2dX
            czJ0MHpSNGFpTnRwWXJqeVN4Yk9aWlEKLS0tIDJHek1wK0lVZjJLU05hT0hVS3k5
            c3FMSFc5SlRRZXU1SUJnRjFDcEViR00K2j3hv0J+OPCYGDDkwrLmfDYO7XasBA/p
            IJ5Inr4O5EGCkzRn/SLRMdiPx3CvGU2RGLP/7pJXqd4nWNrdd40g5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T15:06:11Z"
    mac: ENC[AES256_GCM,data:3InO9f/zcYpLGXy/EtaQ9bGKfVK/QB5BhPG97nvbAxNUpS87pje0ckS7syQHN05hfif63BcKLc3cAsu5moIT8RRf1WXi6TMM5pMAaBt3SSxtUHxdsAErENA74mwRRnNfwernKnLnXEKtkapFVJfWh51dMxDABczix3x1o6RLGmQ=,iv:ULIQ9R+YoYbLp8MPFJkpJsZYxefTMkUCMfBKLblUz/c=,tag:hqZ69FE+707lyzpMamAgYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
