apiVersion: v1
kind: Secret
metadata:
    name: harbor-config
    namespace: dev
stringData:
    #ENC[AES256_GCM,data:VM6H+IVoYcIdGHDhBDa/SQhxK2YzMtr9qZNesRwbFI/B2FHmbthqE4X9C/J/FRm7eAuQIwk3dbddP0uPnmyUVqlcNeH9PrrF4PTMdrrWbfKPJx4B5LedRZk2aVsNMNKQI75kT33ZriVq5UD5hkj9CPToimsFO8RkBpC0O7P58Pid6Pn88/qStnGmIXiHwVsOlcZIOGVB4r0=,iv:ZbWQJdtMP0xdPvKVbwuJuUIEc+y079YE8WrabUX6PA8=,tag:afmpNH/kWaduC1kQoMh/tg==,type:comment]
    CONFIG_OVERWRITE_JSON: ENC[AES256_GCM,data:M267Zb4a61B0M6GmS666q/c6adgNKGGmkj14/JPtFRT6eRpAtEICOFjUeyrR7+7scUmPz+UegGw+X8dlRky3l3D2gUOh65NPJLbdrPZGGjAfFpqxFYUTthJvHE8BHx21CT3p/CwxaLBNtzokgy5v6nTM1CYlUnJU1b8H5QF3Hfo5n2534ijmqP7xQJZMvciLyb3v7iKT3jJuPFe32BE9/ohMOJIkzPeR5BpEnSefXkRlV6PcicCMmS0HuYxpvtk6fDOdloqrfmsi6ngd6tGVHiiIfWql4SocFLEeJJQBNXSs+ZpFXz/K1vxmxThAykzTzgLGKuRzxhHmenEXdQO7HVkiN0UiIowNNA5HNHpIh7xBLFXDfA1iBqxdCVslx/IRE2u9Wz3SGRJgVc4O01JMn3S7F7e561pDXcZ5Xv9FxBjLOMFRW2n4UIvJfTQyx9shI0E+klywR3Rduyjb2V8n8rUY8vfjPeNLYjigkw4mrUd3MacpB/bMfCwwcpf1WJ4ZIcx93+/aKCKtZc3ZzvS3vkPaakkgkDwj1l35uBJsiiT0zbXtrUxuVFQ6o6kqXH7DgigRaHP4y7rUZ270bK1VYTvcXtj29yg3lzo1pVaD7T29Dmy+AvNMIdIlSLnewomD2NNaoEdKHbnPa1lQzQS4JplDHn6eQ1IRDTb24E8AKYqTruIA+2Vef7bPcdZdbLXzQSfVxvEdWX1wolENhrVLFqFwA7qHrXol/Vb8S196e5HVOPU2aYzy9GmQKd9oivZpwTQ9wmi/Y6A7LgXh806jmH922UXwWSfvwK4fe6o8NSZlJdVptvrQbK+Gxc6MOHwjxSeP8BrpluiH7+xSs+CmL5ZjFwTTKTASLefscGvQc3C2K8Jmww0QuQyE7Omp9ywVhkHtAk4bCAmI527y2de0CysGInDazZSU3es0Os3Fgilv7bdrJo92sxN918KmO06lWYyde53yeaELJS4/qwTkSJIKEhwZ6cBc4neq/JcGma5gNGH7Y8iQ3radpZhx+cClHxP0i0gmaQ3TR4wZryL9wNlKMRxdGMiyXoeAh8XVeRyXCKh7GuLHesVfjs6FH93G6DRNMV6BvYE1KdlMAiy6ZVmlDqM5PKD+eYvCwrwqUUUlHhz0XJ0cjYDyGe3iCmMDlvHxkYHMGA==,iv:ye2XgEj4Fzxkd6ScrMvXxqzS3IkYOCP6P04bda9iel0=,tag:bGBJFYJR0DvjaINY9Ybi3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cg8jk89nugmrn3rylak4shyaq2ssgvp2g6975884zp3u2t8klenqx9cnau
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cFJnR0JnRDJqVWdEcFEv
            Z2tISnQveTRuY3JPNWFjWldreTdwaytyM0UwCk93TlpIYWo3OVJMMm16ZVVLTnZX
            NU90Qjh4YUlzRlRZVmE2eG0vT2ttSEUKLS0tIFVoNzZGL2wxd3ZETWtOV0RGYjE2
            L2cwd3k5eUF2Z0hzWlQ0YmREa2ZYWDgKh73wZ9jBsKZv/CF1L+d3qn5JqsilaJRl
            MmZ+4prJxhSLhIVXhdF6Wm0watAxuZK47eVMlFLxCieA9MmMy4n9zA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T15:42:34Z"
    mac: ENC[AES256_GCM,data:MxbYu3VOUxnLlD+Ojz5p3viRyaSKs+nPFlsfzTrpo1T6L5Q5OzYfrdar6W1S+9ujJ9T2Xwr/6vEN42d2K2fEEtVS0BNjt5C15KzoBXgbK2RGdUCf5o/MGzgTzX9OpHwDo3Oz+XxwFsan4liv3Z4v/bOjJkRtF88h9WUdSA4jQDY=,iv:QB04BP2k+rAL7c0JtKxftQp4Mk+ke/hJuMWBZh+HjrI=,tag:CSW0e813akL5mn8UDqnsng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
