apiVersion: v1
kind: Secret
metadata:
    name: ldap-user-manager-env
    namespace: networking
stringData:
    LDAP_URI: ENC[AES256_GCM,data:3ohyEfs34Rxlzf9RAC3LH4M6uaOAdMjcnOrJBbniQ0FnORaacdtvCMFI3D67UBiu,iv:LPQZKg2TYZB5fQnhuiBJismd5TdXBLyP+AxEWBrdL8o=,tag:i+gcKqqeUiTROlt9xlZdig==,type:str]
    LDAP_BASE_DN: ENC[AES256_GCM,data:mtCLrEkyiLwuyq7+xnV7BHcPfGJVC80=,iv:QscBbyI81HwkPfZC+k2Bkvq3YoB3DcBAsFzPd5YyB64=,tag:H3KLejeREGtTA+hyt/NmSg==,type:str]
    LDAP_ADMIN_BIND_DN: ENC[AES256_GCM,data:3LSc9ImxVjQTUuTDmUMgHEFCoUfqiglk5meOVx9xWjs=,iv:DbdOSY+hkbtqdxmSiBJyILT8i76JrF+fwdoGFUCQmik=,tag:mgRPKvIIY33rf6WzBrU65Q==,type:str]
    LDAP_ADMIN_BIND_PWD: ""
    LDAP_ADMINS_GROUP: ENC[AES256_GCM,data:L6On3r1H,iv:fM/kooDbDiUPpTWeys/uP6ifVKROXyqop0kpgLTe5qk=,tag:sdBynB0swKEhb7O/WEE2lQ==,type:str]
    LDAP_USER_OU: ENC[AES256_GCM,data:3dTfiOwA,iv:ZqIqOpkiiE3Lg9TB0pg1czbvbtD7CnavOE3DqCib8hM=,tag:c5iv/c2bVEQVnz8AA0/4eA==,type:str]
    LDAP_GROUP_OU: ENC[AES256_GCM,data:3i8mudIM,iv:rlM2NVRNOUUnnd2zCjmkFZfqGAzphtYr8oA4jeaXrj8=,tag:dVHnUMqdGKwvMf6TgIsymg==,type:str]
    LDAP_ACCOUNT_ATTRIBUTE: ENC[AES256_GCM,data:nVBr,iv:Z1RGA1Y6X9EAlnEaFDyycysTbYkdRkx8CuPd8nK8874=,tag:r0iL0T03VhLA2Dj0W2EB4g==,type:str]
    LDAP_GROUP_MEMBERSHIP_ATTRIBUTE: ENC[AES256_GCM,data:5mW1SBK7Rr/HJDbj,iv:YMUQDZFFndIQax8qM88M3E2FfPE5063vXw9fYsrrTOQ=,tag:JK4fCLNADIjWvcrQSpQYrA==,type:str]
    LDAP_REQUIRE_STARTTLS: ENC[AES256_GCM,data:MzqsotM=,iv:YhYovgiWqFYfdshFIbRp7ga/hjz4DLiytV53Afd+nbU=,tag:eyUJFoyqug9Uv9AoSuOhxw==,type:str]
    DEFAULT_USER_GROUP: ENC[AES256_GCM,data:DjKS808=,iv:a3X6NGRi9ZoiRKfeB/ZquVm8UxvXcbnPQcxmR29aRP0=,tag:fHFNltcMro1iyGuJWBidlg==,type:str]
    EMAIL_DOMAIN: ""
    USERNAME_FORMAT: ENC[AES256_GCM,data:S2Oo+TlnOI0yxJGP,iv:ZW+7RjmNy3mv8C5vLNZ60qYhaLOL0uwF1R+YQ+VBNqQ=,tag:0qn4CA1AaoViUqAosCmnVw==,type:str]
    SMTP_HOSTNAME: ""
    SMTP_HOST_PORT: ENC[AES256_GCM,data:RB1a,iv:+yzhSsO06JugVzAVvWJivqT5+LJSqOT2AYo0fOrxxok=,tag:Etdim92GdztL26IkALPmQQ==,type:str]
    SMTP_USERNAME: ""
    SMTP_PASSWORD: ""
    SMTP_USE_TLS: ENC[AES256_GCM,data:cEUFgA==,iv:HwoehS4gnH1/xkoAgDIcN20vHg0JHpTmmU6546VMoAU=,tag:hWVIDkm9hP+8N8eqyBOckQ==,type:str]
    NO_HTTPS: ENC[AES256_GCM,data:CrIdRQ==,iv:tekA1ReJGrwbrReAa7PzLCwhefGPaPaUI4r3yJflFn0=,tag:SY31TR5eu0swvT0Xn9QBsg==,type:str]
    ACCOUNT_REQUESTS_EMAIL: ""
    ACCOUNT_REQUESTS_ENABLED: ENC[AES256_GCM,data:flMHsQ==,iv:W606wEvcEUVoQMR5GeMg4/vWuNTLCHE6Eq6iqrf8D1A=,tag:ag2Fi52RUpnxQKfhcfCtqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cg8jk89nugmrn3rylak4shyaq2ssgvp2g6975884zp3u2t8klenqx9cnau
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1NXM3MkhEVWdabEtwWm1G
            Z3V5NWxGdjAwTU9BRWJJWUxXZmw3dlBxLzJnCkxWMzd2UHBtbEZKNk5lN203QjF6
            QUl2THJpSzhFSGpZdHI5OWN1Uk1jTWMKLS0tIEJFaEMzeldEdGhrVGlkNSt2eEVo
            OEFWTUZoY3MyNUtSY1ZXZkc2QXZxemsKWX53J0CYP3O06iiWc0spyQbuy4wk4fsG
            4BD2WT42QyLY4gkfcCYskERX0y1dJYMRUObaHU89MWH5XeNnFTDKBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T15:42:34Z"
    mac: ENC[AES256_GCM,data:ipH2/oaIvnprDDEq3RS8Be1yTZ8B/Ka3L7sSpRFXxzl3It+QGLpgZ83wzT7r8IC69Sz0cM6U0ypwdTMRgQtwuK2xnE34OYNyuczjGWGmt4SbaYTEY8kFUR16avRkWrDYD6Jgiyv104seOSWnVDPNJ09bBGSxhUhtJMamObDvUwg=,iv:JHYUQDdS7oX+kE++NcR5a1Zpp8qRrcWdtcWUCA3Iq3k=,tag:8Ys94dBCQPAFVf6bQF4TBA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
