apiVersion: v1
kind: Secret
metadata:
    name: k10-dr-secret
    namespace: kasten-io
stringData:
    key: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cg8jk89nugmrn3rylak4shyaq2ssgvp2g6975884zp3u2t8klenqx9cnau
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMc1pBZ3F0a1RKWVg5RnYv
            Ni92RXlxS1RmSmd6VEZCMTB1Tlc1Q3U3T1ZRCjViSFRGQVJQZ1pYeG5yZkVGeXZN
            M013S0pYclhhZXdBc1N6aThTL04zdWMKLS0tIDhxWVN1T2R2Y0cwb0IvRVlJTGZT
            NjEvaFBjRkhDSWNkMlQwSDIwZUdHVkUKQvW+5Z//N6ITXje3PxsCpKeY56Qz+mTB
            YbEbYRFvP78qAZ458T4iJHMwTlBOhfv8XU/Hk5fnvGItOGGzYSNlqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T06:55:19Z"
    mac: ENC[AES256_GCM,data:De3KfIdOsLph+4NEsJ8Zq3gLdNoIiQwv1j6++KoqUuftfDMmud1EryDL4km1VBmyQ2OYyy299HgXyGpB1xAe/qYFPWMFl2UCYYtnRe4qJQ2G0ONoS1cTKhRQO9GCzZU95aGsjBzN14yQLP/r20SbgiZdphHekzLlKqiJHE0IEkU=,iv:Up6cG1jMjY8R3i7G3QUVSzFPJI/7dtYI1tDQdfb/hB4=,tag:mUDneJZqKFqRn71OLLG6Gw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
