apiVersion: v1
kind: Secret
metadata:
    name: k10-dr-secret
    namespace: kasten-io
stringData:
    key: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cg8jk89nugmrn3rylak4shyaq2ssgvp2g6975884zp3u2t8klenqx9cnau
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMmY4YTlCL3NhNys4U01k
            dmhPWXRocmlGRkwrMis4RUtCMldyY2N3eWk0CjcvVWdQMEp5Z1dPTk91c0pISWgv
            NlBiQnlaOFEvNy8xNXdaeHlvbnlsUkUKLS0tIEVhL0RmZ0pabTNwZXJuaGUrSi8v
            NFppUW9IRzBDclhnb3NjRm1wOUkwQzgKmft7CKap11rkK+CHe8U0Y2aUydgHX3lD
            nVLZiidArz79Sp5zNZnHqJFXe66gZHQy7fxg/zK8mU9D5DJLN4ZIWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T18:09:22Z"
    mac: ENC[AES256_GCM,data:K52BvdMTnHPSEkjPcTuAA9hntyrw6/dvgbYWmF7Nyh1GX6Dq/fuEt986BvFkrvLCtHEpHL0iwJ5yZgco45HHD1KQbIekjknur9mIe9DPNOrCAQTalvxtU5tIsOMyiMYH0KAunL1tHs3DsNQhEeyz82zHt55ev8tb3hEayRlnqfQ=,iv:PgbZ88cLB5d6Y9Dds5EBIm/q4mJOJSi2YumDIolVmSc=,tag:Cq4vdaczr00W2BjHx4qCkw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
