apiVersion: v1
kind: Secret
metadata:
    name: k10-dr-secret
    namespace: kasten-io
stringData:
    key: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cg8jk89nugmrn3rylak4shyaq2ssgvp2g6975884zp3u2t8klenqx9cnau
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTFIzRnF2SjVZMXBUZ0lp
            Zi9Vam4wcGVNSnpkejRReVgyZGdVQUd0SzJrCkVMd2ltc1ZJR3RCTTA3Z1JCcUcx
            cFM3Vm5yRHZJQk4wRVRmcTRLZE1TOHcKLS0tIFZmZnJkSnFRTjRYZ0hoc1EveXBC
            STVSQTRySVBDMS9CQmxwTHV3K05odWMKg5pQkcLJaGcvemzydz0UiujG39RgDHbG
            S0SsTk63n7IbCiJ+pBXUTx7XWSUSF6hSSxo2KIEFsCRZj7dl7LRD+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T15:42:34Z"
    mac: ENC[AES256_GCM,data:oHFppSxhC8E4fr+IbSIozR+8xxHe3v8BBXg/kHILVPKIy9Zn1P+a8UG5qCFIoXkRxPbOjIfROpp9sC/H4nVpqjfhW+c/GXd5q/QpYW1qoYGwLHOOn+IcIEcBJuoOOt2BwhATaA/ALbe4RlE1TqvDsUMCuChTBvdYPLJmhFxMTCs=,iv:LSXD6Sru48/CjrPpibZStgQ+XU/ao+TjnW+F3+g2VIg=,tag:ZTL48i5rTRQ1xz+LIkc/eg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
